# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(max_length=512, verbose_name='Reminder text')),
                ('delay', models.IntegerField(verbose_name='Reminder delay')),
            ],
        ),
    ]
