# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Board name')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tasks', to='task.Task')),
            ],
        ),
    ]
